mrkkrp/megaparsec

CHANGELOG.md
Text/Megaparsec/Lexer.hs
Text/Megaparsec/Prim.hs
tests/Lexer.hs

Advanced combinators for indentation-sensitive parsing

---

CHANGELOG.md
README.md
Text/Megaparsec.hs
Text/Megaparsec/Combinator.hs
Text/Megaparsec/Expr.hs
Text/Megaparsec/Lexer.hs
Text/Megaparsec/Prim.hs
megaparsec.cabal
old-tests/Bugs/Bug9.hs
stack.yaml
tests/Char.hs
tests/Prim.hs
tests/Util.hs

Implementation of the recovery feature.
TODO list:

Implement the recovery feature

---

CHANGELOG.md
Text/Megaparsec/Lexer.hs
tests/Lexer.hs
tests/Prim.hs
tests/Util.hs

This PR add the line-folding functionality and should address #87.
Progress:

Line folding

---

Text/Megaparsec/Prim.hs

Clarify error message for `many` parser

---

Text/Megaparsec.hs
Text/Megaparsec/Prim.hs
tests/Text/Megaparsec/PrimSpec.hs

Should hopefully resolve #115.

Add debugging primitive

---

CHANGELOG.md
Text/Megaparsec/Prim.hs
tests/Text/Megaparsec/PrimSpec.hs

Add the ‘observing’ primitive

---

CHANGELOG.md
Text/Megaparsec/Prim.hs
tests/Test/Hspec/Megaparsec/AdHoc.hs
tests/Text/Megaparsec/PrimSpec.hs

Add more MTL instances

---

CHANGELOG.md
Text/Megaparsec/Combinator.hs
Text/Megaparsec/Prim.hs

Performance tweaks

---

CHANGELOG.md
Text/Megaparsec/Lexer.hs
tests/Text/Megaparsec/LexerSpec.hs

Fix subtle ‘indentBlock’ bugs, add new tests

---

CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Prim.hs
tests/Text/Megaparsec/PrimSpec.hs

Implement the ‘match’ combinator

---

CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Prim.hs
tests/Text/Megaparsec/PrimSpec.hs

Add the ‘region’ combinator

---

CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Prim.hs
tests/Text/Megaparsec/PrimSpec.hs

Add ‘getNextTokenPosition’

---

CHANGELOG.md
Text/Megaparsec/Error.hs
tests/Text/Megaparsec/ErrorSpec.hs

Display control characters in strings nicely

---

CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Error.hs
Text/Megaparsec/Lexer.hs
Text/Megaparsec/Pos.hs
Text/Megaparsec/Stream.hs
bench/memory/Main.hs
bench/speed/Main.hs
megaparsec.cabal
stack.yaml
tests/Test/Hspec/Megaparsec.hs
tests/Test/Hspec/Megaparsec/AdHoc.hs
tests/Text/Megaparsec/CharSpec.hs
tests/Text/Megaparsec/ErrorSpec.hs
tests/Text/Megaparsec/LexerSpec.hs
tests/Text/Megaparsec/PosSpec.hs
tests/Text/MegaparsecSpec.hs

Refactor pos and error modules

---

Text/Megaparsec.hs
Text/Megaparsec/Error/Builder.hs

Documentation improvements

---

.travis.yml
CHANGELOG.md
README.md
Text/Megaparsec.hs
Text/Megaparsec/Byte.hs
Text/Megaparsec/Char.hs
Text/Megaparsec/Error.hs
Text/Megaparsec/Lexer.hs
Text/Megaparsec/Perm.hs
megaparsec.cabal
tests/Text/Megaparsec/ByteSpec.hs
tests/Text/Megaparsec/CharSpec.hs
tests/Text/Megaparsec/ErrorSpec.hs

Char and byte modules

---

AUTHORS.md
CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Error.hs
Text/Megaparsec/Stream.hs
tests/Text/Megaparsec/ErrorSpec.hs

Resolves #205, continuation of #233.

Implement rendering of parse error context

---

CHANGELOG.md
Text/Megaparsec/Error.hs
tests/Text/Megaparsec/ErrorSpec.hs

Fix rendering of offending line with tabs

---

CHANGELOG.md
Text/Megaparsec.hs
tests/Text/MegaparsecSpec.hs

Add hint erasing when try backtracks consuming

---

CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Char.hs
tests/Text/MegaparsecSpec.hs

Simplify the type of the ‘token’ primitive

---

CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Byte.hs
Text/Megaparsec/Byte/Lexer.hs
Text/Megaparsec/Char.hs
Text/Megaparsec/Char/Lexer.hs
Text/Megaparsec/Pos.hs
tests/Text/Megaparsec/ByteSpec.hs
tests/Text/Megaparsec/CharSpec.hs
tests/Text/Megaparsec/StreamSpec.hs
tests/Text/MegaparsecSpec.hs

This is a work in progress, it'll take a while.
Close #263.

Move and rename token-independent parsers

---

CHANGELOG.md
Text/Megaparsec.hs
Text/Megaparsec/Byte/Lexer.hs
Text/Megaparsec/Char/Lexer.hs
tests/Text/Megaparsec/Byte/LexerSpec.hs
tests/Text/Megaparsec/Char/LexerSpec.hs

Fix backtracking of exponent and fractional parts in numeric helpers

---

CHANGELOG.md
Text/Megaparsec/Error.hs
tests/Text/Megaparsec/ErrorSpec.hs

Implement continuous highlighting in parse errors

---

Text/Megaparsec/Error.hs

Fixed typo (staring -> 'String')

---

CHANGELOG.md
Text/Megaparsec/Byte.hs
Text/Megaparsec/Byte/Lexer.hs
Text/Megaparsec/Char.hs
Text/Megaparsec/Char/Lexer.hs
Text/Megaparsec/Common.hs
Text/Megaparsec/Lexer.hs
megaparsec.cabal

Stream specific modules should not import form each other.

Refactoring of stream-specific modules

---

Text/Megaparsec/Error/Builder.hs

More descriptive error when elabel or ulabel is used incorrectly

---

.travis.yml
Text/Megaparsec/Stream.hs
bench/memory/Main.hs
bench/speed/Main.hs
megaparsec-tests/megaparsec-tests.cabal
megaparsec-tests/tests/Text/Megaparsec/Byte/LexerSpec.hs
megaparsec-tests/tests/Text/Megaparsec/ByteSpec.hs
megaparsec-tests/tests/Text/Megaparsec/Char/LexerSpec.hs
megaparsec-tests/tests/Text/Megaparsec/CharSpec.hs
megaparsec-tests/tests/Text/Megaparsec/DebugSpec.hs
megaparsec-tests/tests/Text/Megaparsec/ErrorSpec.hs
megaparsec-tests/tests/Text/Megaparsec/PosSpec.hs
megaparsec-tests/tests/Text/Megaparsec/StreamSpec.hs
megaparsec-tests/tests/Text/MegaparsecSpec.hs
megaparsec.cabal

Test with GHC 8.8.1 on CI

---

Text/Megaparsec/Class.hs

Close #462.
Applying simplification to structure while keeping the important information.

Megaparsec.Class.MonadParsec: token: upd docs

---

CHANGELOG.md
Text/Megaparsec/Byte/Binary.hs
bench/memory/Main.hs
bench/speed/Main.hs
megaparsec-tests/megaparsec-tests.cabal
megaparsec-tests/tests/Text/Megaparsec/Byte/BinarySpec.hs
megaparsec.cabal

Machine number parsers (Word16/32/64, both endians)

---

Text/Megaparsec/Class.hs

During study/work seeing what is missing from official docs (haddocks) or what is hard to understand from them, and making the patch.

Small doc update

---

megaparsec.cabal

Allow text-2.0

---

CHANGELOG.md
Text/Megaparsec/Internal.hs
megaparsec-tests/megaparsec-tests.cabal
megaparsec-tests/tests/Text/MegaparsecSpec.hs

https://hackage.haskell.org/package/mtl-2.3/changelog

Support mtl-2.3

---

megaparsec-tests/megaparsec-tests.cabal
megaparsec.cabal

This corresponds to support for the latest 3 GHC versions.

Request minimal base 4.15

---

CHANGELOG.md
Text/Megaparsec/Stream.hs

Fixes https://github.com/mrkkrp/megaparsec/issues/486

Make St SourcePos strict and UNPACKed

---

CHANGELOG.md
Text/Megaparsec/Internal.hs
megaparsec-tests/tests/Text/MegaparsecSpec.hs

Make label override all hints instead of only the last one

---

Text/Megaparsec.hs

Point out that 'parse' and 'runParser' are the same

---

CHANGELOG.md
Text/Megaparsec/Stream.hs
megaparsec-tests/tests/Text/Megaparsec/ErrorSpec.hs
megaparsec-tests/tests/Text/Megaparsec/StreamSpec.hs

Render tabs correctly when error messages are rendered
