- Text/MegaParsec/Token.hs
According to this post
(http://blog.ezyang.com/2014/05/parsec-try-a-or-b-considered-harmful/),
the error message could be confusing if using `try`. `"3.a"` is one case
to expose this behavior.
> Remove `try` in float parser.

- benchmarks/Main.hs
- megaparsec.cabal
This code benchmarks the "string" primitive and various non-primitive combinators.
The code coverage of these benchmarks is not 100%: new benchmarks should be added
as relevant performance questions are discovered.
This closes #7.
> Add a few synthetic benchmarks

- Text/Megaparsec.hs
- Text/Megaparsec/ByteString.hs
- Text/Megaparsec/ByteString/Lazy.hs
- Text/Megaparsec/Char.hs
- Text/Megaparsec/Combinator.hs
- Text/Megaparsec/Expr.hs
- Text/Megaparsec/Lexer.hs
- Text/Megaparsec/Perm.hs
- Text/Megaparsec/Prim.hs
- Text/Megaparsec/String.hs
- Text/Megaparsec/Text.hs
- Text/Megaparsec/Text/Lazy.hs
- megaparsec.cabal
- old-tests/Bugs/Bug9.hs
- tests/Expr.hs
- tests/Prim.hs
This branch contains various changes made according to issue #27.
The changes include:
* elimination of built-in backtracking user state
* introduction of type class `MonadParsec` and corrections in type signatures of most tools to work smoothly with any instance of `MonadParsec`, not only `ParsecT`.
Criticism and practical testing are welcome.
> Monad transformer

- megaparsec.cabal
- tests/Prim.hs
This brings coverage to 82%; it could be made even higher by replicating more tests for `ReaderT` and `IdentityT`, but it feels like... cheating? Also I can't think of any non-trivial tests for `getParserState` and `updateParserState` that would be related to `StateT`.
> Add some tests for monad transformers (see #27)

- README.md
- Text/Megaparsec/ByteString.hs
- Text/Megaparsec/ByteString/Lazy.hs
- Text/Megaparsec/Char.hs
- Text/Megaparsec/Combinator.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Lexer.hs
- Text/Megaparsec/Perm.hs
- Text/Megaparsec/Prim.hs
- Text/Megaparsec/String.hs
- Text/Megaparsec/Text.hs
- Text/Megaparsec/Text/Lazy.hs
- megaparsec.cabal
- old-tests/Bugs/Bug9.hs
- tests/Char.hs
- tests/Error.hs
- tests/Expr.hs
- tests/Lexer.hs
- tests/Pos.hs
- tests/Util.hs
This PR basically introduces a bunch of CPP `#if`s to import additional operators from `Control.Applicative` (in most cases) or `Data.Foldable` (in one case). See #42 for the original issue.
I didn't change the existing `import Control.Applicative` lines, since they would lead to redundant import warnings on GHC 7.10.x, and instead put the `#if MIN_VERSION` makros at the end of all imports in all files. in all files that used only `<$>` in one place, I replaced `<$>` by infix `fmap` to keep the number of changes per file a little bit smaller.
While I was at it, I also removed the "recent version of `base`" comment in the readme, since it works now with an older one (by the way, base-4.6 compatibility seems possible, currently experimenting).
Things left to do:
-----
- the fixity …
> Add compatibility to GHC 7.8.x

- Text/Megaparsec/Error.hs
- Text/Megaparsec/Prim.hs
- megaparsec.cabal
- old-tests/Bugs/Bug39.hs
- tests/Error.hs
- tests/Expr.hs
- tests/Lexer.hs
- tests/Perm.hs
- tests/Prim.hs
This version introduces several `#if` for `bool` from `Data.Bool`, and (in one case), for `isLeft` and `isRight`.
Since this approach isn't really clean, I suggest to remove compatibility to base-4.6.0.0 on the second patch release of GHC 8.0, or considering an additional (single) module for those functions (if GHC 7.6 compatibility is a long term concern).
(Sorry, that took a while, I ran into some `sh` trouble due to some incompatibilities between several msys versions and couldn't install `time-*`. That's what I get for running Windows.)
This PR fixes #46.
> Add base-4.6.0.x compatiblity

- Text/Megaparsec/Prim.hs
This avoids subtle performance issues and makes the code more
future proof.
> Canonicalise Applicative/Monad instances

- stack.yaml
Any reason not to update to the latest Stack LTS? Seems like [Travis is happy](https://travis-ci.org/stackbuilders/megaparsec/builds/101284089).
> Update stack to latest LTS 4.0

- CHANGELOG.md
- Text/Megaparsec/Combinator.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Prim.hs
- tests/Prim.hs
Close #81.
This solution is mostly OK as it passes tests and almost all benchmarks show that there is no performance degradation.
The only function that bothers me is `pPlus` (or `mplus`, or `<|>`). Benchmarks `choice/match`, `choice/nomatch`, and `manyTill` show about 44 % worse performance with current implementation of the feature — this is not acceptable. All these functions are defined via `mplus`, so it's necessary to find a way to improve that function.
Also, `mplus` is tricky in that it combines different branches of parsing. Previously, all logic describing how to combine failing branches into one `ParseError` were in `mergeError` function. Now we have to have `longestMatch` function to choose right state as well, because it's natural to expect that state on failure would …
> Support getting actual parser state on failure

- .travis.yml
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Lexer.hs
- Text/Megaparsec/Prim.hs
- megaparsec.cabal
This also enables the respective warnings flags in dev mode
to help megaparsec forward compatible.
The dependencies on `semigroup` and `fail` are conditional on
`impl(ghc >= 8)` and avoid CPP and conditionally defined instances
(which would result in an conditional API).
> Define MonadFail & Semigroup instances

- CHANGELOG.md
- Text/Megaparsec/Char.hs
- Text/Megaparsec/Combinator.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Pos.hs
- Text/Megaparsec/Prim.hs
- megaparsec.cabal
- tests/Pos.hs
- tests/Prim.hs
- tests/Util.hs
This PR aims to improve experience of users who work with custom input streams. In particular with such streams where tokens have start/end positions attached (for example when input stream is generated by alex/happy).
TODO list:
> More flexible position-advancing function

- Text/Megaparsec.hs
The `alphaNum` parser was renamed to `alphaNumChar`, yet the docs
weren't full updated to reflect this change.
> Reflect renaming of alphaNum in docs

- Text/Megaparsec/Pos.hs
`Pos` is a newtype wrapper around `Word` and the `unsafePos` function
is marked `INLINE`, so `unsafeCoerce` is complete overkill.
> Remove un-needed unsafeCoerce

- Text/Megaparsec/Lexer.hs
- tests/Text/Megaparsec/LexerSpec.hs
Even though the haddock for `Text.Megaparsec.Lexer.space` says that
Parsing of white space is an important part of any parser. We
propose a convention where every lexeme parser assumes no spaces
before the lexeme and consumes all spaces after the lexeme;
all the indentation-sensitive parsing combinators assume/consume
whitespace _before_ the thing to be parsed. This would normally mean
they can't be used with combinators like `many` and `some` without using
`try` (and sacrificing performance). Fortunately `indentBlock` also
consumes whitespace _after_, but unfortunately it didn't do that in the
`IndentNone` case. Now it does and it works with many and some without
try!  \o/
> Make indentBlock/IndentNone work with many like IndentMany/Some does

- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Prim.hs
- tests/Test/Hspec/Megaparsec.hs
- tests/Text/Megaparsec/PrimSpec.hs
Close #170.
OK, there is actually a lot of work to be done, off the top of my head:
> Count processed tokens

- .travis.yml
- megaparsec.cabal
- tests/Spec.hs
This is a PR that instroduces the change, but we don't want to merge it yet. Support for GHC 7.6 will be dropped at some point though, probably after release of version 5.2. Related: #165.
> Drop support for GHC 7.6

- CHANGELOG.md
- Text/Megaparsec/Error.hs
This can be used to discard unnecessary error information in simplistic parsers.
> Make () an error component

- CHANGELOG.md
- Text/Megaparsec/Prim.hs
- megaparsec.cabal
- tests/Text/Megaparsec/PrimSpec.hs
> Define ‘Semigroup’ and ‘Monoid’ for ‘ParsecT’

- CHANGELOG.md
- Text/Megaparsec.hs
- tests/Text/MegaparsecSpec.hs
Example usage:
``` haskell
{-# LANGUAGE RecursiveDo, TypeApplications #-}
import Text.Megaparsec
import Text.Megaparsec.Char
import Control.Monad.Fix
import Data.Void
withRange
:: (MonadParsec e s m, MonadFix m)
=> ((SourcePos,SourcePos) -> m a)
-> m a
withRange f = do
Just pos1 <- getNextTokenPosition
rec
r <- f (pos1, pos2)
pos2 <- getPosition
return r
main = do
parseTest @Void (withRange $ \pp -> (,) pp <$> string "ab") "abcd"
```
> Add a MonadFix ParsecT instance

- .travis.yml
- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Byte.hs
- Text/Megaparsec/Byte/Lexer.hs
- Text/Megaparsec/Char.hs
- Text/Megaparsec/Char/Lexer.hs
- Text/Megaparsec/Error.hs
- bench/memory/Main.hs
- bench/speed/Main.hs
- megaparsec.cabal
- tests/Test/Hspec/Megaparsec/AdHoc.hs
- tests/Text/Megaparsec/Byte/LexerSpec.hs
- tests/Text/Megaparsec/Char/LexerSpec.hs
- tests/Text/Megaparsec/PermSpec.hs
> Speed-up numeric parsers

- CHANGELOG.md
- Text/Megaparsec.hs
- tests/Text/MegaparsecSpec.hs
> Use ‘eok’ continuation in tokens when matching empty chunk

- .travis.yml
- CHANGELOG.md
- Text/Megaparsec/Byte/Lexer.hs
- Text/Megaparsec/Char/Lexer.hs
- megaparsec.cabal
- tests/Text/Megaparsec/Byte/LexerSpec.hs
- tests/Text/Megaparsec/Char/LexerSpec.hs
> Make ‘float’ consume only floating point literals

- Text/Megaparsec/Char/Lexer.hs
I could trigger it with the following: `char '"' *> manyTill L.charLiteral (char '"')` and the imput `"\154972\&1"`
> Fix `charLiteral` for long character escape sequences

- megaparsec.cabal
- tests/Text/Megaparsec/Char/LexerSpec.hs
- tests/Text/Megaparsec/CharSpec.hs
Close #308.
Apparently it's quite complicated to make case-insensitive matching perfect, so I guess we'll just preserve the logic we currently have because it's a nice compromise between speed/simplicity and decent level of correctness.
Here let's just make sure that we don't get non-deterministic test suite failures.
> Fix rare test failures related to ‘string'’

- Text/Megaparsec/Error.hs
See https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6#UndecidableInstancesispickier.
With this change, I am able to build on GHC 8.6.1-beta1.  Without it, the four uses of `Token s` in instance heads give errors.
> UndecidableInstances needed in one module for GHC 8.6.

- Text/Megaparsec/Internal.hs
- tests/Text/MegaparsecSpec.hs
Close #316.
In particular, don't prepend the phrase “the rest of ”.
> Do not alter labels artificially

- CHANGELOG.md
- Text/Megaparsec/Error.hs
- tests/Text/Megaparsec/ErrorSpec.hs
Previously the question sign `?` was erroneously inserted before offending line in 2nd and later parse errors.
> Fix a bug in ‘errorBundlePretty’

- Text/Megaparsec/Class.hs
Commit 56c89cba24903a966678c3508deeff8a0af0b68e removed a CPP
conditional.  mtl Control.Monad.Identity only exports
Control.Monad.Trans.Identity as of v2.2.2.  Therefore IdentityT is
not in scope with mtl < v2.2.2. and the build fails.
Restore the CPP block to fix building with mtl < v2.2.2.
> Fix build with mtl < v2.2.2

- CHANGELOG.md
- Text/Megaparsec/Byte/Lexer.hs
- Text/Megaparsec/Char/Lexer.hs
Close #356.
It appears that we can relax constraints for `decimal`, `binary`, `octal`, and `hexadecimal` from `Integral` to `Num` keeping the same implementations.
> Generalize numeric parsers in lexer modules

- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Stream.hs
- megaparsec-tests/src/Test/Hspec/Megaparsec/AdHoc.hs
- megaparsec-tests/tests/Text/Megaparsec/ErrorSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/StreamSpec.hs
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
Close #344.
Changed type signatures of `reachOffset` and `reachOffsetNoLine` methods of the `Stream` type class. Instead of three-tuple `reachOffset` now returns two-tuple because `SourcePos` is already contained in the returned `PosState` record.
> Simplify type signatures of ‘reachOffset’ and ‘reachOffsetNoLine’

- README.md
Here's a new Megaparsec-derived package for the list of related packages in the README.
https://hackage.haskell.org/package/replace-megaparsec
> README Related packages: Add replace-megaparsec

- .travis.yml
- CHANGELOG.md
- Text/Megaparsec/Class.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Error/Builder.hs
- Text/Megaparsec/Internal.hs
- Text/Megaparsec/Pos.hs
- Text/Megaparsec/Stream.hs
- megaparsec-tests/megaparsec-tests.cabal
- megaparsec-tests/src/Test/Hspec/Megaparsec/AdHoc.hs
- megaparsec-tests/tests/Text/Megaparsec/Char/LexerSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/CharSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/ErrorSpec.hs
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
- megaparsec.cabal
Currently blocked on dependencies. In particular: https://github.com/bos/aeson/pull/697. Let's wait a bit.
> Drop remaining CPP, drop support for GHC 8.2.x

- CHANGELOG.md
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Stream.hs
Currently, the `errorItemLength` function implicitly assumes that every token spans exactly one character. That assumption is correct for the `Stream` instances for the basic string types (`String`/`Text`/`ByteString`) included in Megaparsec. It does not necessarily hold for custom token types however, in particular if using a separate lexer pass.
This commit adds a new `tokensLength` function that allows the `Stream` instance to give a custom width for a non-empty token stream.
In practice, parse errors concerning a token with a width greater than 1 are currently rendered incorrectly (only one caret is displayed below the offending token).
> Allow Stream to specify custom token width

- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Class.hs
- Text/Megaparsec/Internal.hs
- default.nix
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
- nix/patches/dhall.patch
Close #381.
The methods `failure` and `fancyFailure` of `MonadParsec` are now ordinary functions and live in `Text.Megaparsec`. They are defined in terms of the new `parseError` method of `MonadParsec`. This method allows us to signal parse errors at a given offset without manipulating parser state manually.
TODO:
> Re-organize error reporting functions

- .travis.yml
- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Class.hs
- Text/Megaparsec/Debug.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Error.hs-boot
- Text/Megaparsec/Internal.hs
- Text/Megaparsec/State.hs
- default.nix
- megaparsec-tests/src/Test/Hspec/Megaparsec/AdHoc.hs
- megaparsec-tests/tests/Text/Megaparsec/Byte/LexerSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/ByteSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/ErrorSpec.hs
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
- nix/patches/dhall.patch
- nix/patches/hledger-lib.patch
- nix/patches/hspec-megaparsec.patch
- nix/patches/idris.patch
- nix/patches/mmark.patch
- nix/patches/parser-combinators-tests.patch
Close #359.
Megaparsec now supports registration of “delayed” parse errors. On lower level we added a new field called `stateParseErrors` to the `State` record. The type also had to change from `State s` to `State s e`. This field contains the list of registered `ParseErrors` that do not end parsing immediately but still will cause failure in the end if the list is not empty. Users are expected to register parse errors using the three functions: `registerParseError`, `registerFailure`, and `registerFancyFailure`. These functions are analogous to those without the `register` prefix, except that they have “delayed” effect.
TODO:
> Allow registration of delayed parse errors

- .travis.yml
Now that we published `hspec-megaparsec-2.1.0` with support for Megaparsec 8 we can resume testing with Cabal on CI.
> Restore testing on CI

- Text/Megaparsec/Class.hs
`anyChar` was renamed to `anySingle` in 7.0.0 - this simply updates the outdated comment
> Update comment to reflect updated function name

- megaparsec-tests/tests/Text/Megaparsec/ByteSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/CharSpec.hs
Alphanumeric characters are not generated often enough so QuickCheck may
sometimes give up on this one. The function is defined analogous to other
similar functions so there is really no point in testing it.
> Remove the tests for ‘alphaNumChar’

- CHANGELOG.md
- Text/Megaparsec/Byte.hs
- Text/Megaparsec/Char.hs
- Text/Megaparsec/Char/Lexer.hs
- Text/Megaparsec/Stream.hs
- megaparsec-tests/tests/Text/Megaparsec/ByteSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/Char/LexerSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/CharSpec.hs
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
Close #408.
These functions are slightly more specific versions of the existing `space` functions. They accept only “horizontal whitespace”.
> Add ‘hspace’ and ‘hspace1’ functions

- .github/workflows/ci.yaml
- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Byte.hs
- Text/Megaparsec/Byte/Lexer.hs
- Text/Megaparsec/Char.hs
- Text/Megaparsec/Char/Lexer.hs
- Text/Megaparsec/Debug.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Internal.hs
- Text/Megaparsec/Stream.hs
- cabal.project
- default.nix
- megaparsec-tests/tests/Text/Megaparsec/ErrorSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/StreamSpec.hs
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
- nix/nixpkgs/default.nix
- nix/patches/dhall.patch
- nix/patches/hspec-megaparsec.patch
- nix/patches/idris.patch
- nix/patches/tomland.patch
This adds two new classes `StreamDebug` and `StreamError`, and moves these methods to them:
- `StreamDebug`: `showTokens`, `tokensLength`.
- `StreamError`: `reachOffset`, `reachOffsetNoLine`.
This allows users to implement `Stream` for streams where the token type is more complex and those methods may be difficult to implement.
This also adds `ListLikeStream` (name WIP) which lets you use `DerivingVia` for implementing `Stream` on newtypes over `[]` or `Seq`.
This PR addresses #388 and #413.
> Decouple debug and error reporting methods from Stream

- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Byte.hs
- Text/Megaparsec/Byte/Lexer.hs
- Text/Megaparsec/Char.hs
- Text/Megaparsec/Char/Lexer.hs
- Text/Megaparsec/Class.hs
- Text/Megaparsec/Common.hs
- Text/Megaparsec/Debug.hs
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Error/Builder.hs
- Text/Megaparsec/Internal.hs
- Text/Megaparsec/Lexer.hs
- Text/Megaparsec/Pos.hs
- Text/Megaparsec/State.hs
- Text/Megaparsec/Stream.hs
Remove dependence on GeneralizedNewtypeDeriving and add Safe Haskell
extensions to every file. Closes #425
> Add Safe Haskell support

- megaparsec-tests/megaparsec-tests.cabal
- megaparsec.cabal
Tested using
```cabal
packages: megaparsec.cabal
, megaparsec-tests/megaparsec-tests.cabal
constraints:
bytestring >= 0.11
allow-newer:
text:bytestring
```
> Allow bytestring-0.11

- Text/Megaparsec/Lexer.hs
The Haddock links for `space1` don't currently go anywhere.  This PR fixes these links:
https://hackage.haskell.org/package/megaparsec-9.0.1/docs/Text-Megaparsec-Char-Lexer.html
My guess is that `Text.Megaparsec.Char.Lexer` was imported qualified as `C`, so the links used to work, but that import has since been removed.
> Fix Haddock link to Text.Megaparsec.Char.space1

- CHANGELOG.md
- Text/Megaparsec/Debug.hs
> Add a debugging helper that doesn't require a `Show` instance

- CHANGELOG.md
- Text/Megaparsec/Debug.hs
- megaparsec-tests/megaparsec-tests.cabal
- megaparsec-tests/src/Test/Hspec/Megaparsec/AdHoc.hs
- megaparsec-tests/tests/Text/Megaparsec/DebugSpec.hs
Close #488.
`MonadParsecDbg` class and instances for `MonadParsecT`, `ReaderT`, `WriterT`, `StateT` and `RWST` added.
There are some difficulties with testing these changes, because they use `trace` and thefore can not be tested by `hspec`. To work around this, I've added separate `test-debug` executablle into `megaparsec-tests` for running some parsers manually and checking produced ouput with my eyes. Maybe, this is not a good solution, but I have not found any better.
Futhermore, I have no `nix-shell` and it will be not very easy to run tests (I'm working on Windows). For instance, the `cabal test all` failed with `commitBuffer: invalid argument (invalid character)`. I don't think that my changes should break anything, however.
> Add a type class for parser monads with debugging

- CHANGELOG.md
- Text/Megaparsec/Stream.hs
Closes https://github.com/mrkkrp/megaparsec/issues/492
As mentioned in the issue, we can avoid leaking memory retaining the input in memory by explicitly copying token sequences as we read them.
The performance implications of adding an explicit `copy` to `takeN_` and `takeWhile_` are as follows:
- The `takeWhileP` family of basic combinators end up consuming a lot more memory (since previously they didn't need to allocate the result buffer) and time (due to the `copy` call).
- The `decimal` (`octal` etc) family of combinators are about 40% slower and consume about twice as much memory. 
- All other combinators (like `many`) have either stayed the same or got slightly (up to 10%) faster.
Sadly we don't have any real-world benchmarks (or do we?) so it's hard to tell if this would have any …
> Explicitly copy token sequences to avoid sharing input

- README.md
this takes into account https://markkarpov.com/post/megaparsec-7.html#parsercombinators-grows-megaparsec-shrinks
> documentation: mention `parser-combinators` as a related package

- CHANGELOG.md
- Text/Megaparsec/Debug.hs
- Text/Megaparsec/Error.hs
- megaparsec-tests/tests/Text/Megaparsec/DebugSpec.hs
This is convinient for figuring out where your labels are lost during parsing process.
I had to add `showErrorItem` to `Text.Megaparsec.Error` exports to use it for printing hints in `Text.Megaparsec.Debug`. Maybe there's any better solution. Moreover, there can be many styles of printing hints. I've chosen list-like:
```
HINTS: ['a', 'b', end of file]
```
> Print hints in `dbg` method

- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Internal.hs
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
Closes #528.
I'm not sure about MonadCont and MonadFix instances -- to be honest, I haven't ever used them and don't understand properly, how they should work. At the moment they clear all hints like before.
> Preserve hints in monad transformers operations

- CHANGELOG.md
- Text/Megaparsec/Class.hs
- Text/Megaparsec/Debug.hs
- Text/Megaparsec/Internal.hs
- Text/Megaparsec/Internal.hs-boot
- megaparsec-tests/tests/Text/MegaparsecSpec.hs
Close #366.
Implements a new primitive as discussed in https://github.com/mrkkrp/megaparsec/issues/366#issuecomment-1434839814, which enables defining new primitives, at the cost of needing to drop (a little) into megaparsec internals.
> Implement mkParsec—a new method of MonadParsec

- CHANGELOG.md
- Text/Megaparsec/Debug.hs
- Text/Megaparsec/Internal.hs
> Remove not strictly necessary Monad m constraints introduced in #514

- CHANGELOG.md
- Text/Megaparsec/Internal.hs
A general function `hoistP` can be used to implement monad transformer class methods of the form `MonadFoo m => m (f a) -> m (g a)` for example `local`, `listen` and `pass`. Usage of `hoistP` becomes more ergonomic when `Result` and `Reply` have `Traversable` instances.
> Add MonadWriter instance

- megaparsec-tests/megaparsec-tests.cabal
- megaparsec.cabal
The versions `5.0` and `5` are not the same.
If you write `base < 5.0`, you accept `base-5` but reject `base-5.0.*`.
This is usually not intended.
The correct format for upper bounds is `< ver` where `ver` has no trailing 0s.
> Formal correction of dep upper bounds: `< x.0` to `< x`

- .github/workflows/ci.yaml
- megaparsec-tests/megaparsec-tests.cabal
- megaparsec.cabal
Otherwise, one might get errors like
```
Error: cabal: Could not resolve dependencies:
[__0] trying: ormolu-0.7.2.0 (user goal)
[__1] trying: th-env-0.1.1 (dependency of ormolu)
[__2] trying: template-haskell-2.21.0.0/installed-54dc (dependency of th-env)
[__3] trying: pretty-1.1.3.6/installed-8ddc (dependency of template-haskell)
[__4] trying: megaparsec-9.5.0 (dependency of ormolu)
[__5] next goal: Cabal-syntax (dependency of ormolu)
[__5] rejecting: Cabal-syntax-3.10.2.0/installed-6d41 (conflict: megaparsec =>
bytestring>=0.2 && <0.12, Cabal-syntax => bytestring==0.12.0.2/installed-66e0)
[__5] rejecting: Cabal-syntax-3.10.1.0 (conflict: pretty =>
deepseq==1.5.0.0/installed-2833, Cabal-syntax => deepseq>=1.3.0.1 && <1.5)
[__5] rejecting: Cabal-syntax-3.8.1.0 (conflict: ormolu => …
```
> Update for GHC 9.8 

- CHANGELOG.md
- megaparsec.cabal
#539 exported `initialState` and `initialPosState`, and the CHANGELOG for 9.6.0 indicated that these are now available for use.  Unfortunately, they are not, since they were exported from `Text.Megaparsec.State`, which itself is not exported from the package.  This PR simply moves `Text.Megaparsec.State` from `other-modules` to `exported-modules` to allow `initialState` and `initialPosState` to be used as advertised.
If another solution is considered more desirable (*e.g.* re-exporting `initialState` and `initialPosState` from some other module) I'd be happy to modify the PR or open a new one.
> Move `Text.Megaparsec.State` into `exposed-modules`

- Text/Megaparsec.hs
- parsers-bench/ParsersBench/CSV/Attoparsec.hs
- parsers-bench/ParsersBench/CSV/Megaparsec.hs
GHC doesn't seem to inline or fuse the infix version of `elem/notElem`.  Fully expanding their uses does allow it.
csv benchmarks get faster and `satisfy (\x -> x == '\'' || x == '\"') = oneOf ['\'', '\"']` now holds with regards to performance. Note that `oneOf "'\""` will still be slower, which is why I left the note unchanged.
> Expand elem/notElem to allow fusion

- CHANGELOG.md
- Text/Megaparsec/Error.hs
- Text/Megaparsec/Stream.hs
- Text/Megaparsec/Unicode.hs
- megaparsec-tests/megaparsec-tests.cabal
- megaparsec-tests/tests/Text/Megaparsec/ErrorSpec.hs
- megaparsec-tests/tests/Text/Megaparsec/UnicodeSpec.hs
- megaparsec.cabal
> Implement correct handling of wide Unicode characters

- CHANGELOG.md
- Text/Megaparsec/Internal.hs
The applicative operators `*>` and `<*` are not inlined in the generated GHC Core, so I added `INLINE` pragmas to them. As a result, parsing CSV and JSON takes around 40% less time when running the benchmarks on my machine.
> Inline applicative operators

- Text/Megaparsec/Internal.hs
Sorry for bothering with PR just for such small typo, but it really confused me for some time. I had to dig the sources and Hoogle for such function before I finally realized it was a typo.
> chore: fix typo in `mzero` docs

- CHANGELOG.md
- Text/Megaparsec.hs
- Text/Megaparsec/Internal.hs
> Use better implementations for many and some by default

- CHANGELOG.md
- Text/Megaparsec/Error.hs
If you use `errorBundlePretty` when writing a [GHC pre-processor](https://downloads.haskell.org/ghc/latest/docs/users_guide/phases.html#pre-processor) then error output does not look pretty:
To address this, this PR adds `errorBundlePrettyForGhcPreProcessors`, which results in:
Details:
1. When a GHC pre-processor fails, then GHC parses source locations and error messages from the pre-processor's output.
2. Multi-line error messages have to be ***indented***, otherwise GHC won't parse them properly.
3. When GHC pretty-prints error message it indents multi-line error messages by ***four spaces***, but it ***does not strip any whitespace*** from parsed error messages before pretty-printing them.
As a consequence, the best you can achieve for a pre-processor is to have multi-line error …
> Add `Text.Megaparsec.Error.errorBundlePrettyForGhcPreProcessors`
